name: Build and Test

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle Wrapper
        run: |
          # Check if wrapper exists
          if [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "Gradle wrapper not found, generating it..."
            # Create directories if they don't exist
            mkdir -p gradle/wrapper
            # Copy the wrapper files from your local machine
            echo "Copying gradle-wrapper.jar"
            curl -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar
            echo "Copying gradle-wrapper.properties"
            cat > gradle/wrapper/gradle-wrapper.properties << 'EOL'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOL
          else
            echo "Gradle wrapper found"
          fi

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Verify Plugin
        run: ./gradlew verifyPlugin
