name: Release Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

# Permissions needed for creating releases
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Make scripts executable
        run: |
          chmod +x ./gradlew
          chmod +x get-current-version.sh
          chmod +x bump-version.sh
          
          # Debug: Show current version
          echo "Current version information:"
          ./get-current-version.sh

      - name: Calculate next version
        id: calculate_version
        run: |
          # Determine if this is a prerelease
          SNAPSHOT_FLAG=""
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.prerelease }}" == "true" ]]; then
            SNAPSHOT_FLAG="--snapshot"
          fi
          
          # Use the bump-version script to calculate the next version (patch increment)
          NEW_VERSION=$(./bump-version.sh build.gradle patch $SNAPSHOT_FLAG)
          
          # Set the output variable for use in later steps
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version will be: $NEW_VERSION"

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Create Git Tag
        run: |
          git tag -a v${{ steps.calculate_version.outputs.new_version }} -m "Release v${{ steps.calculate_version.outputs.new_version }}"
          git push origin v${{ steps.calculate_version.outputs.new_version }}

      - name: List Distribution Files
        run: |
          echo "Listing files in build/distributions:"
          ls -la build/distributions/

      - name: Create GitHub Release
        id: create_release
        run: |
          # Find the built plugin ZIP file
          PLUGIN_ZIP=$(find build/distributions -name "*.zip" | head -n 1)
          if [ -z "$PLUGIN_ZIP" ]; then
            echo "No ZIP file found in build/distributions. Using wildcard pattern."
            PLUGIN_ZIP="build/distributions/*.zip"
          fi
          echo "Found plugin ZIP: $PLUGIN_ZIP"

          # Create a release using GitHub CLI
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.prerelease }}" == "true" ]]; then
            gh release create v${{ steps.calculate_version.outputs.new_version }} "$PLUGIN_ZIP" \
              --title "Release v${{ steps.calculate_version.outputs.new_version }}" \
              --notes "Automated release v${{ steps.calculate_version.outputs.new_version }}" \
              --prerelease
          else
            gh release create v${{ steps.calculate_version.outputs.new_version }} "$PLUGIN_ZIP" \
              --title "Release v${{ steps.calculate_version.outputs.new_version }}" \
              --notes "Automated release v${{ steps.calculate_version.outputs.new_version }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Plugin to JetBrains Marketplace
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.prerelease) }}
        run: |
          if [ -n "${{ secrets.INTELLIJ_MARKETPLACE_TOKEN }}" ]; then
            ./gradlew publishPlugin
          else
            echo "INTELLIJ_MARKETPLACE_TOKEN not set, skipping marketplace upload"
          fi
        env:
          INTELLIJ_MARKETPLACE_TOKEN: ${{ secrets.INTELLIJ_MARKETPLACE_TOKEN }}
