name: Release Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

# Permissions needed for creating releases
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Calculate next version
        id: calculate_version
        run: |
          # Extract current version from build.gradle
          CURRENT_VERSION=$(grep -oP "version '\K[^']+" build.gradle)
          echo "Current version: $CURRENT_VERSION"

          # Remove -SNAPSHOT suffix if present
          CURRENT_VERSION=${CURRENT_VERSION%-SNAPSHOT}

          # Split version into components
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}

          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          # Add -SNAPSHOT suffix for prerelease
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.prerelease }}" == "true" ]]; then
            NEW_VERSION="${NEW_VERSION}-SNAPSHOT"
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version will be: $NEW_VERSION"

      - name: Update version in build.gradle
        run: |
          sed -i "s/version '.*'/version '${{ steps.calculate_version.outputs.new_version }}'/" build.gradle
          cat build.gradle

          # Commit the version change
          git add build.gradle
          git commit -m "Bump version to ${{ steps.calculate_version.outputs.new_version }}"
          git push

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Create Git Tag
        run: |
          git tag -a v${{ steps.calculate_version.outputs.new_version }} -m "Release v${{ steps.calculate_version.outputs.new_version }}"
          git push origin v${{ steps.calculate_version.outputs.new_version }}

      - name: Create GitHub Release
        id: create_release
        run: |
          # Find the built plugin ZIP file
          PLUGIN_ZIP=$(find build/distributions -name "*.zip" | head -n 1)
          echo "Found plugin ZIP: $PLUGIN_ZIP"

          # Create a release using GitHub CLI
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.prerelease }}" == "true" ]]; then
            gh release create v${{ steps.calculate_version.outputs.new_version }} "$PLUGIN_ZIP" \
              --title "Release v${{ steps.calculate_version.outputs.new_version }}" \
              --notes "Automated release v${{ steps.calculate_version.outputs.new_version }}" \
              --prerelease
          else
            gh release create v${{ steps.calculate_version.outputs.new_version }} "$PLUGIN_ZIP" \
              --title "Release v${{ steps.calculate_version.outputs.new_version }}" \
              --notes "Automated release v${{ steps.calculate_version.outputs.new_version }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Plugin to JetBrains Marketplace
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.prerelease) }}
        run: |
          if [ -n "${{ secrets.INTELLIJ_MARKETPLACE_TOKEN }}" ]; then
            ./gradlew publishPlugin
          else
            echo "INTELLIJ_MARKETPLACE_TOKEN not set, skipping marketplace upload"
          fi
        env:
          INTELLIJ_MARKETPLACE_TOKEN: ${{ secrets.INTELLIJ_MARKETPLACE_TOKEN }}
